### ISSUE TITLE
Database - Put the old data Archives page

### ISSUE THREAD

**Issue by MarineMontailler** [WildCodeSchool/lyon-p3-sens-interdit#24]
As developer, i need to work with de old data to fill the archives pages and test the code

**Comment by Seblecaribou** [comment]
After a lot of research and extracting from the original WordPress website, we have a _clean_ JSON with all the archives that we can actually do something with.

The decision we took was to use that JSON file to fill a separate collection of spectacles and a separate collection of festivals, nicknamed globally "old archives" since the data extracted is too different from the new data that will be inserted in the future. It will then be a front end job to display it with a different component so that it resemble as close as possible, the new design for the new app.
